/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChainLinkFX_JNIBridge */

#ifndef _Included_ChainLinkFX_JNIBridge
#define _Included_ChainLinkFX_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    initPA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChainLinkFX_JNIBridge_initPA
  (JNIEnv *, jclass);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    terminatePA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChainLinkFX_JNIBridge_terminatePA
  (JNIEnv *, jclass);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ChainLinkFX_JNIBridge_getDeviceCount
  (JNIEnv *, jclass);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    addChain
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ChainLinkFX_JNIBridge_addChain
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    removeChain
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ChainLinkFX_JNIBridge_removeChain
  (JNIEnv *, jclass, jint);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    addChainLink
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ChainLinkFX_JNIBridge_addChainLink
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    removeChainLink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ChainLinkFX_JNIBridge_removeChainLink
  (JNIEnv *, jclass);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    constructDevice
 * Signature: (I)LChainLinkFX/Device;
 */
JNIEXPORT jobject JNICALL Java_ChainLinkFX_JNIBridge_constructDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     ChainLinkFX_JNIBridge
 * Method:    setParameter
 * Signature: (IIIF)I
 */
JNIEXPORT jint JNICALL Java_ChainLinkFX_JNIBridge_setParameter
  (JNIEnv *, jclass, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
